Assignment5/urls.py
from django.contrib import admin
from app.views import *
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name="home"),
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login" ),
    path('logout/', views.logout, name="logout"),
    
    path('create_project/', views.create_project, name="create_project"),
    #The following url gives the link to edit a specific project using the project id
    path('edit_project/<int:project_id>', views.edit_project, name="edit_project"),
    
    #Django has built in views for password reset. However, I created my own templates for password reset
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='users/reset_password.html'), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='users/email_sent.html'), name="password_reset_done"),
    #The following path will encode the users id and a base 64 encription
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/create_new_password.html'), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/new_password_confirmed.html'), name="password_reset_complete")
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager  ,PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

class UserManager(BaseUserManager):
    def create(self, email, fname, lname, password=None, **extra_fields):
        if not email:
            raise ValueError("Please enter a valid email")
        
        email = self.normalize_email(email)
        user = self.model(email=email, fname=fname, lname=lname)
        user.set_password(password)
        user.save(using=self._db)
        return user
        
    def create_superuser(self, email, password=None, **extra_fields):
            extra_fields.setdefault("is_staff", True)
            extra_fields.setdefault("is_superuser", True)
            
            if extra_fields.get('is_staff') is not True:
                raise ValueError("Superuser must have staff = True")
            
            if extra_fields.get('is_superuser') is not True:
                raise ValueError("Superuser must be true")
            return self.create(email, password, **extra_fields)
            
        
class User(AbstractBaseUser, PermissionsMixin):
    fname = models.CharField(verbose_name="First Name",  max_length=50)        
    lname = models.CharField(verbose_name="Last Name",  max_length=50)
    email = models.EmailField(verbose_name="Email",unique=True)
    date_joined = models.DateTimeField(_('date_joined'), default=timezone.now)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager() 
     
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['fname', 'lname']
    
    
    def first_name(self):
        return self.fname
    
    def full_name(self):
        return f"{self.fname} {self.lname}"
    
    def __str__(self):
        return self.email
    
    
class Project(models.Model):
    title = models.CharField(max_length=50)
    owner = models.ForeignKey(User, on_delete= models.CASCADE)
    description = models.TextField(default="No description has been added")
    created = models.DateTimeField(default=timezone.now())
    
    def __str__(self):
        return self.title

app/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, PasswordChangeForm
from django.utils.translation import gettext_lazy as _

class RegisterForm(UserCreationForm):
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=100, widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['fname','lname', 'email', 'password', 'confirm_password']
    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')    
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError('Passwords do not match')
        return confirm_password
    #Clean email function filters through the emails
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email has already been taken")
    def save(self, commit=True):
        user = super().save(commit=False)  
        user.set_password(self.cleaned_data('password'))  
        if commit:
            user.save()
        return user    
        
class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['email', 'password']

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description']
        
#This form will allow an email to be sent for password reset        
class PasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label = _("Email"), widget= forms.EmailInput())
    
class ResetPasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].widget = forms.PasswordInput(attrs={'placeholder': 'New Password'})
        self.fields['new_password2'].widget = forms.PasswordInput(attrs={'placeholder': 'Confirm Password'})
        
    def save(self, commit=True):
        return super().save(commit)
            

app/templates/users/create_new_password.html
{%extends 'users/main.html'%}
{%block content%}
<div class="container">
    <div class="row vh-100 align-items-center justify-content-center">
        <div class="col-sm-12">
            <div class="card p-4 shadow mx-auto">
                <div class="card-header bg-white">
                    <h2 class="text-center text-primary">Change Your Password</h2>
                </div>
                <div class="card-body ">
                    <form method="POST">
                        {%csrf_token%}
                        {{form.as_p}}
                        <button class="btn btn-primary w-100" type="Submit">Reset Password</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

app/templates/users/email_sent.html
{%extends 'users/main.html'%}
{%block content%}
<div class="container">
    <div class="row vh-100 align-items-center justify-content-center">
        <div class="col-12 text-center center-text text-primary ">
            <h3 class="m-4">Thank You! A link has been sent to your email</h3>
            <h5>Please make sure you check your spam folder!</h5>
        </div>
    </div>
</div>
{%endblock%}

app/templates/users/login.html
{%extends 'users/main.html'%}
{%block title %}Login{% endblock %}
{%block content%}
<div class="container">
    <div class="row vh-100 align-items-center justify-content-center">
        <div class="col-sm-12">
            <div class="card p-4 shadow mx-auto">
                <div class="card-header bg-white">
                    <h2 class="text-center text-primary">Login</h2>
                </div>
                <div class="card-body">
                    <form method="POST" action="{%url 'home'%}">
                        {% csrf_token %}
                        <div class="form-group">
                            {{form.as_p}}
                        </div>
                        <button type="submit" class="btn btn-primary w-100" value="register">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

app/templates/users/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Project</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/style.css'%}">
    <script src="https://kit.fontawesome.com/3c45431b42.js" crossorigin="anonymous"></script>
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg mb-5 navbar-light bg-primary p-4 fixed-top">
        <a class="navbar-brand text-white" href="{%url 'home'%}">Projects</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> 
            <span class="navbar-toggler-icon text-white outline-none"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="navbar-item"><a class="nav-link text-white" href="{%url 'login'%}">Login</a></li>
            <li class="navbar-item"><a class="nav-link text-white" href="{%url 'register'%}">Register</a></li>
          </ul>
        </div>
    </nav>
    <main class="mt-5">
        {%block content%}

        {%endblock%}
    </main>
    <footer class="footer ">
        <div class="container">
          <div class="row">
            <div class="col-lg-4">
              <h5>About Us</h5>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
            <div class="col-lg-4">
              <h5>Contact</h5>
              <p>Email: info@example.com</p>
              <p>Phone: +1 123 456 7890</p>
            </div>
            <div class="col-lg-4">
              <h5>Follow Us</h5>
              <a href="#" class="me-2"><i class="fab fa-facebook-f"></i></a>
              <a href="#" class="me-2"><i class="fab fa-twitter"></i></a>
              <a href="#" class="me-2"><i class="fab fa-instagram"></i></a>
            </div>
          </div>
        </div>
      </footer>

    <script src="{% static 'users/script.js' %}"></script>
</body>
</html>

app/templates/users/new_password_confirmed.html
{%extends 'users/main.html'%}
{%block content%}
<div class="container">
    <div class="row vh-100 align-items-center justify-content-center">
        <div class="col-12 text-center center-text text-primary ">
            <h3 class="m-4">Your New Password Has Been Confirmed!</h3>
            <p>Log in <a class="p4 text-white bg-primary" href="{%url 'login'%}">Here</a></p>
        </div>
    </div>
</div>
{%endblock%}

app/templates/users/register.html
{%extends 'users/main.html'%}
{%block title %}Register{% endblock %}
{%block content%}
<div class="container">
    <div class="row v-100 align-items-center justify-content-center">
        <div class="col-sm-12">
            <div class="card p-4 shadow mx-auto">
                <div class="card-header bg-white">
                    <h2 class="text-center text-primary">Register</h2>
                </div>
                <div class="card-body ">
                    <form method="POST" action="{%url 'register'%}">
                        {% csrf_token %}
                        <div class="form-group mt-4">
                            <label for="id_fname">First Name</label>
                            {{form.fname}}
                        </div>
                        <div class="form-group mt-4">
                            <label for="id_lname">Last Name</label>
                            {{form.lname}}
                        </div>
                        <div class="form-group mt-4">
                            <label class="w-25" for="id_email">Email</label>
                            {{form.email}}
                        </div>
                        <div class="form-group mt-4">
                            <label class="w-25" for="id_password">Password</label>
                            {{form.password}}
                        </div>
                        <div class="form-group mt-4">
                            <label class="w-25" for="id_confirm_password">Confirm Password</label>
                            {{form.confirm_password}}
                        </div>
                        {% if error_message %}
                            <p class="text-center center-text text-danger">{{error_message}}</p>
                        {% endif %}
                        <p class="text-center center-text mb-0">Already have an account? <a href="{%url "login"%}">Log In</a></p>
                        <button type="submit" class="btn btn-primary w-100" value="register">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}

app/templates/users/reset_password.html
{%extends 'users/main.html'%}
{%block content%}
<div class="container">
    <div class="row vh-100 align-items-center justify-content-center">
        <div class="col-sm-12">
            <div class="card p-4 shadow mx-auto">
                <div class="card-header bg-white">
                    <h2 class="text-center text-primary">Password Reset</h2>
                </div>
                <div class="card-body ">
                    <form method="POST">
                        {%csrf_token%}
                        <div class="row">
                            <p class="text-center center-text">Please enter your email address</p>
                            <div class="col-sm-2">
                                {{form.email.label_tag}}
                            </div>
                            <div class="col-sm-9">
                                {{form.email}}
                            </div>
                        </div>
                        
                        <button class="btn btn-primary w-100" type="Submit">Reset Password</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}